### ISSUE TITLE
DragonAntiPvPLeaver not work on MCPC+

### ISSUE THREAD

**Issue by CAJIO** [IDragonfire/DragonAntiPvPLeaver#24]
Add support MCPC+

https://github.com/MinecraftPortCentral/MCPC-Plus

**Comment by Bubelbub** [comment]
Errors? Log?

**Comment by CAJIO** [comment]
No, just does not work.

**Comment by IDragonfire** [comment]
Can you post your plugins settings?
What happen if you activate the debug mode?

**Comment by IDragonfire** [comment]
duplicated 
https://github.com/IDragonfire/DragonAntiPvPLeaver/issues/31
