### ISSUE TITLE
MCPC server - Reached end of stream for null

### ISSUE THREAD

**Issue by npdev453** [IDragonfire/DragonAntiPvPLeaver#31]
21:18:23 [SEVERE] Reached end of stream for null
21:18:23 [SEVERE] Reached end of stream for null
21:18:23 [SEVERE] Reached end of stream for null
21:18:23 [SEVERE] Reached end of stream for null
21:18:23 [SEVERE] Reached end of stream for null
21:18:23 [SEVERE] Reached end of stream for null

**Comment by npdev453** [comment]
2013-08-05 21:19:54 [INFO] [VoxelSniper] Enabling VoxelSniper v5.168.6-SNAPSHOT-jnks218
2013-08-05 21:19:55 [INFO] [DragonAntiPvPLeaver] Enabling DragonAntiPvPLeaver v1.9.6.2.2882
2013-08-05 21:19:55 [INFO] [DragonAntiPvPLeaver] Loaded 0 Dead Players.
2013-08-05 21:19:55 [SEVERE] Reached end of stream for null
2013-08-05 21:19:55 [SEVERE] Reached end of stream for null
2013-08-05 21:19:55 [SEVERE] Reached end of stream for null
2013-08-05 21:19:55 [SEVERE] Reached end of stream for null
2013-08-05 21:19:55 [INFO] [PluginManager] Enabling PluginManager v1.0.2
2013-08-05 21:19:55 [SEVERE] Reached end of stream for null
2013-08-05 21:19:55 [SEVERE] Reached end of stream for null
2013-08-05 21:19:55 [SEVERE] Reached end of stream for null
2013-08-05 21:19:55 [INFO] [MuteManager] Enabling MuteManager v0.12.6

and spams a lot

**Comment by IDragonfire** [comment]
bukkit version?

**Comment by npdev453** [comment]
2013-08-06 23:10:47 [INFO] [Inheritance] Inheritance added javassist/ClassPathList parents 1
2013-08-06 23:10:47 [SEVERE] javassist.NotFoundException: net.minecraft.server.v1_6_R2.PlayerConnection
2013-08-06 23:10:47 [SEVERE]    at javassist.ClassPool.get(ClassPool.java:450)
2013-08-06 23:10:47 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Transformer.transform(DAPL_Transformer.java:125)
2013-08-06 23:10:47 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Plugin.onEnable(DAPL_Plugin.java:73)
2013-08-06 23:10:47 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-08-06 23:10:47 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
2013-08-06 23:10:47 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
2013-08-06 23:10:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.loadPlugin(CraftServer.java:312)
2013-08-06 23:10:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.enablePlugins(CraftServer.java:294)
2013-08-06 23:10:47 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:487)
2013-08-06 23:10:47 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:451)
2013-08-06 23:10:47 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:403)
2013-08-06 23:10:47 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
2013-08-06 23:10:47 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
2013-08-06 23:10:47 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2013-08-06 23:10:47 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Human_Manager

**Comment by npdev453** [comment]
1.6.2

**Comment by npdev453** [comment]
> 2013-08-06 23:18:47 [INFO] read eff 9 - 0.0 / 0.0 / 0.0
> 2013-08-06 23:18:47 [INFO] Preparing start region for level 3 (Dimension: -1, Seed: 1537412672)
> 2013-08-06 23:18:47 [INFO] [DragonAntiPvPLeaver] Enabling DragonAntiPvPLeaver v0.2.2
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Transformer
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Transformer parents 1
> 2013-08-06 23:18:47 [INFO] [ReflectionRemapper] ReflectionRemapped found Class forName!
> 2013-08-06 23:18:47 [INFO] [ReflectionRemapper] Remapping net.minecraft.server.DAPL_Injection -> null
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassPool
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/ClassPool parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/NotFoundException
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/NotFoundException parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtClass
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtClass parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtArray
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtArray parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtClassType
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtClassType parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtNewClass
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtNewClass parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtNewNestedClass
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtNewNestedClass parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CannotCompileException
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CannotCompileException parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassPool$1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/ClassPool$1 parents 2
> 2013-08-06 23:18:47 [INFO] [ReflectionRemapper] ReflectionRemapped found Class forName!
> 2013-08-06 23:18:47 [INFO] [ReflectionRemapper] Remapping java.lang.ClassLoader -> null
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassPoolTail
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/ClassPoolTail parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassPath
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/ClassPath parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassMap
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/ClassMap parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtClass$1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtClass$1 parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtClass$DelayedFileOutputStream
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtClass$DelayedFileOutputStream parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtPrimitiveType
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/CtPrimitiveType parents 1
> 2013-08-06 23:18:47 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassClassPath
> 2013-08-06 23:18:47 [INFO] [Inheritance] Inheritance added javassist/ClassClassPath parents 2
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassPathList
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added javassist/ClassPathList parents 1
> 2013-08-06 23:18:48 [SEVERE] javassist.NotFoundException: net.minecraft.server.v1_6_R2.PlayerConnection
> 2013-08-06 23:18:48 [SEVERE]    at javassist.ClassPool.get(ClassPool.java:450)
> 2013-08-06 23:18:48 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Transformer.transform(DAPL_Transformer.java:125)
> 2013-08-06 23:18:48 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Plugin.onEnable(DAPL_Plugin.java:73)
> 2013-08-06 23:18:48 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
> 2013-08-06 23:18:48 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
> 2013-08-06 23:18:48 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
> 2013-08-06 23:18:48 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.loadPlugin(CraftServer.java:312)
> 2013-08-06 23:18:48 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.enablePlugins(CraftServer.java:294)
> 2013-08-06 23:18:48 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:487)
> 2013-08-06 23:18:48 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:451)
> 2013-08-06 23:18:48 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:403)
> 2013-08-06 23:18:48 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
> 2013-08-06 23:18:48 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
> 2013-08-06 23:18:48 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Human_Manager
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Human_Manager parents 2
> 2013-08-06 23:18:48 [INFO] [ReflectionRemapper] ReflectionRemapper found getDeclaredField!
> 2013-08-06 23:18:48 [INFO] [ReflectionRemapper] - not constant field; skipping, prev=org.objectweb.asm.tree.LineNumberNode@1fa40516
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Config
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Config parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/util/Config
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/util/Config parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/util/Comment
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/util/Comment parents 2
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/util/MultiComment
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/util/MultiComment parents 2
> 2013-08-06 23:18:48 [INFO] [DragonAntiPvPLeaver] Loaded 0 dead players.
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Plugin$DAMAGE_MODE
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Plugin$DAMAGE_MODE parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/DamageTrackerConfig
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/DamageTrackerConfig parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/listener/DamageListenerHandler
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/listener/DamageListenerHandler parents 2
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/SpawnCheckerManager
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/SpawnCheckerManager parents 2
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/NearBy
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/NearBy parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/WhitelistChecker
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/WhitelistChecker parents 2
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/UnderAttack
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/UnderAttack parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/listener/DamageCooldownListenerTemplate
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/listener/DamageCooldownListenerTemplate parents 3
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/IfHit
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/spawn/checker/IfHit parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/listener/CommandDamageListener
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/listener/CommandDamageListener parents 3
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/util/Metrics
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/util/Metrics parents 1
> 2013-08-06 23:18:48 [INFO] [ReflectionRemapper] ReflectionRemapped found Class forName!
> 2013-08-06 23:18:48 [INFO] [ReflectionRemapper] Remapping mineshafter.MineServer -> null
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/util/Metrics$Graph
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/util/Metrics$Graph parents 1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/util/Metrics$1
> 2013-08-06 23:18:48 [INFO] [Inheritance] Inheritance added com/github/idragonfire/DragonAntiPvPLeaver/util/Metrics$1 parents 2
> 2013-08-06 23:18:48 [INFO] Server permissions file permissions.yml is empty, ignoring it

**Comment by IDragonfire** [comment]
Never heared from these server framework ...
I try to fix it ...
Any possiblitiy for faster communication?

**Comment by IDragonfire** [comment]
I get different exceptions wiht the last build, can you post your config?

**Comment by IDragonfire** [comment]
k, custom-class-loader: false helps ...
Complety mc is rewritten ... 
how can I contact the author?

**Comment by npdev453** [comment]
Do u have irc? join to channel at irc.esper.net #mcportcentral

**Comment by npdev453** [comment]
with custom-class-loader: false 

> 2013-08-08 11:55:11 [INFO] Preparing start region for level 2 (Dimension: -1, Seed: 1537412672)
> 2013-08-08 11:55:12 [INFO] [DragonAntiPvPLeaver] Enabling DragonAntiPvPLeaver v0.2.2
> 2013-08-08 11:55:12 [SEVERE] javassist.NotFoundException: net.minecraft.server.v1_6_R2.PlayerConnection
> 2013-08-08 11:55:12 [SEVERE]    at javassist.ClassPool.get(ClassPool.java:450)
> 2013-08-08 11:55:12 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Transformer.transform(DAPL_Transformer.java:125)
> 2013-08-08 11:55:12 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Plugin.onEnable(DAPL_Plugin.java:73)
> 2013-08-08 11:55:12 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
> 2013-08-08 11:55:12 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
> 2013-08-08 11:55:12 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
> 2013-08-08 11:55:12 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.loadPlugin(CraftServer.java:312)
> 2013-08-08 11:55:12 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.enablePlugins(CraftServer.java:294)
> 2013-08-08 11:55:12 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:487)
> 2013-08-08 11:55:12 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:451)
> 2013-08-08 11:55:12 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:403)
> 2013-08-08 11:55:12 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
> 2013-08-08 11:55:12 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
> 2013-08-08 11:55:12 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
> 2013-08-08 11:55:12 [INFO] [DragonAntiPvPLeaver] Loaded 0 dead players.

**Comment by npdev453** [comment]
https://github.com/MinecraftPortCentral/MCPC-Plus/issues/74

**Comment by npdev453** [comment]
No movement?

**Comment by IDragonfire** [comment]
wait on response :(

**Comment by IDragonfire** [comment]
No idea what happen, but atm it works!
