### ISSUE TITLE
DAPL v2 *server_owner_help_me*

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/DragonAntiPvPLeaver#32]
New version of DAPL:
https://www.dropbox.com/s/tpucubsiijoe3hv/DragonAntiPvPLeaver.jar

Worked on my 1.6 server.
Please post problem here.

Features:
- new library in the background
  (=> no item duplication, more compatible with other plugins, better updateable for new minecraft versions)
- more spawn options

Edit:
transform
transformed
pushed

are output from me if all works fine ;)

lossmoney, factions, jobs and mcmmo are only placeholder in the config, based on community result.

**Comment by npdev453** [comment]
MCPC # 37  dont want to start 

> 2013-08-07 12:08:16 [INFO] [Inheritance] Inheritance added javassist/CtClass$DelayedFileOutputStream parents 1
> 2013-08-07 12:08:16 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassMap
> 2013-08-07 12:08:16 [INFO] [Inheritance] Inheritance added javassist/ClassMap parents 1
> 2013-08-07 12:08:16 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtClass$1
> 2013-08-07 12:08:16 [INFO] [Inheritance] Inheritance added javassist/CtClass$1 parents 1
> 2013-08-07 12:08:16 [INFO] [Inheritance] Loading plugin class inheritance for javassist/CtPrimitiveType
> 2013-08-07 12:08:16 [INFO] [Inheritance] Inheritance added javassist/CtPrimitiveType parents 1
> 2013-08-07 12:08:16 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassClassPath
> 2013-08-07 12:08:16 [INFO] [Inheritance] Inheritance added javassist/ClassClassPath parents 2
> 2013-08-07 12:08:16 [INFO] [Inheritance] Loading plugin class inheritance for javassist/ClassPathList
> 2013-08-07 12:08:16 [INFO] [Inheritance] Inheritance added javassist/ClassPathList parents 1
> 2013-08-07 12:08:16 [SEVERE] javassist.NotFoundException: net.minecraft.server.v1_6_R2.PlayerConnection
> 2013-08-07 12:08:16 [SEVERE]    at javassist.ClassPool.get(ClassPool.java:450)
> 2013-08-07 12:08:16 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Transformer.transform(DAPL_Transformer.java:125)
> 2013-08-07 12:08:16 [SEVERE]    at com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Plugin.onEnable(DAPL_Plugin.java:73)
> 2013-08-07 12:08:16 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
> 2013-08-07 12:08:16 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
> 2013-08-07 12:08:16 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
> 2013-08-07 12:08:16 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.loadPlugin(CraftServer.java:312)
> 2013-08-07 12:08:16 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.enablePlugins(CraftServer.java:294)
> 2013-08-07 12:08:16 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:487)
> 2013-08-07 12:08:16 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:451)
> 2013-08-07 12:08:16 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:403)
> 2013-08-07 12:08:16 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
> 2013-08-07 12:08:16 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
> 2013-08-07 12:08:16 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
> 2013-08-07 12:08:16 [INFO] [Inheritance] Loading plugin class inheritance for com/github/idragonfire/DragonAntiPvPLeaver/DAPL_Human_Manager

**Comment by IDragonfire** [comment]
Atm only for bukkit server, try to fix it ...
