### ISSUE TITLE
NPC Not Spawning?

### ISSUE THREAD

**Issue by MoeXIV** [IDragonfire/DragonAntiPvPLeaver#39]
Simple enough, The NPC doesn't spawn when a player logs out, or at all :/

**Comment by IDragonfire** [comment]
What bukkit version did you use?

**Comment by MoeXIV** [comment]
The issue was fixed by a restart, but I posted a few more major issues I found. The most recent one explains most.

**Comment by IDragonfire** [comment]
Without any details I cannot fix anything:

Bukkit Version?
Server Version?
Plugin?

...
Can you post a log from your server?

**Comment by MoeXIV** [comment]
No, the spawning of the NPCs, is not the problem anymore.
I think it was just the plugin did not install properly. Issue is fixed.

Issues that need addressing are in more recent "issues".
