### ISSUE TITLE
NPC Keep armor on

### ISSUE THREAD

**Issue by cjm721** [IDragonfire/DragonAntiPvPLeaver#4]
It would be nice if the npc that spawned still had their armor on. possibly config configurable as I can see the benefits either way..

**Comment by IDragonfire** [comment]
Thank you for the suggestion ;)

http://dev.bukkit.org/server-mods/dragonantipvpleaver/#c98

**Comment by IDragonfire** [comment]
https://github.com/IDragonfire/DragonAntiPvPLeaver/commit/efaad225c31e8b4171fa335febff922c1021c64a
